# -x assembler-with-cpp
# gpSP makefile

# Global definitions

VERSION_MAJOR = 3
VERSION_MINOR = 3
VERSION_BUILD = 2

# コンパイル条件の設定
# バージョン表記にtestとBUILD番号を含めるかどうかの設定
TEST_MODE = 1

USE_DEBUG = 0

# WLANのON/OFF
USE_ADHOC = 0

#最大52MBのメモリを使用する
PSP_LARGE_MEMORY = 0

#CPUコアのARMエミュレータを使用する
USE_C_CORE = 0
