# messege file
# Italian

# MSG_RETURN_MENU
#Press X to return to the main menu.
!Premi X per ritornare al menu principale.

# MSG_MENU_DATE
#TIME
!Data e Ora:

# MSG_MENU_BATTERY
#battery LifePercent:%3d%% LifeTime:%3dmin.
!Carica Batteria:%3d%% Autonomia:%3dmin.

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d

# MSG_MAIN_MENU_0
#Graphics and Sound options
!Opzioni Audio/Video

# MSG_MAIN_MENU_1
#Load state from slot: %d
!Carica stato da slot: %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!Salva  stato in slot: %d

# MSG_MAIN_MENU_3
#Savestate options
!opzioni avanzate Savestate

# MSG_MAIN_MENU_4
#Configure gamepad input
!Configurazione Tasti e D-pad

# MSG_MAIN_MENU_5
#Configure analog input
!Configurazione pad analogico

# MSG_MAIN_MENU_6
#Cheats and Miscellaneous options
!trucchi e opzioni varie

# MSG_MAIN_MENU_7
#Load new game
!Carica nuova rom

# MSG_MAIN_MENU_8
#Restart game
!Ricomincia il gioco

# MSG_MAIN_MENU_9
#Return to game
!Ritorna al gioco

# MSG_MAIN_MENU_10
#Exit gpSP
!Termina gpSP

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!Selezionare per configurare i parametri video e il frameskip,\n
!l'audio on/off, le dimensioni del buffer audio e i filtri audio.

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!Carica il savestate, se esistente, dallo slot corrente per la rom\n
!in esecuzione (si vedano le opzioni avanzate per maggiori informazioni)\n
!Premere destra/sinistra su pad digitale per cambiare lo slot corrente.

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!Salva il savestate per il gioco in esecuzione nello slot corrente.\n
!Si veda il menu opzioni avanzate per maggiori informazioni.\n
!Premere destra o sinistra su pad digitale per cambiare lo slot corrente.

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!Seleziona per accedere al menu per caricare, salvare e visionare\n
!il savestate nello slot attualmente selezionato per la rom\n
!in esecuzione (o per caricarlo da un file sulla MS)

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!Seleziona per rimappare i tasti della PSP per emulare i tasti GBA.

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!Seleziona per configurare il funzionamento del pad Analogico della PSP.

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats, set backup behavior, and set device clock\n
#speed.
!Seleziona per gestire Trucchi, settare le modalita' dei salvataggi\n
!e la frequenza del processore.

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!Carica una nuova rom (la rom attualmente in esecuzione sara' terminata).

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!Resetta emulazione della rom attualmente caricata.

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!Seleziona per uscire dal menu e tornare al gioco.

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!Seleziona per chiudere gpSP e tornare alla XMB della PSP o al loader.

# MSG_G_S_MENU_0
#Display scaling: %s
!Proporzioni Video: %s

# MSG_G_S_MENU_1
#Screen filtering:  %s
!Filtri Grafici:    %s

# MSG_G_S_MENU_2
#Frameskip type:    %s
!modalita salto frame: %s

# MSG_G_S_MENU_3
#Frameskip value:   %d
!N. frame da saltare:  %d

# MSG_G_S_MENU_4
#Frameskip variation:  %s
!Modalita salto frame: %s

# MSG_G_S_MENU_5
#Audio output: %s
!output Audio: %s

# MSG_G_S_MENU_6
#Audio buffer: %s
!buffer Audio: %s

# MSG_G_S_MENU_7
#screen shot
!screen shot

# MSG_G_S_MENU_8
#Back
!Ritorna

# MSG_G_S_MENU_9
#TV output ratio       : %s
!TV output ratio       : %s

# MSG_G_S_MENU_10
#TV output interlace   : %s
!TV output interlace   : %s

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!Determina come ridimensionare il video del GBA rispetto allo schermo PSP\n
!unscaled 3:2 - mantiene la risoluzione originale del GBA,\n
!scaled 3:2   - altezza schermo GBA uguale a quella del video della PSP,\n
!fullscreen   - riempie tutto lo schermo della PSP.

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant.
#colors.
!Determina se usare o meno il filtro bilineare quando il video\n
!viene ridimensionato per adattarsi allo schermo della PSP.\n
!Selezionare questa opzione produce un'immagine piu' uniforme e\n
!morbida, ma piu'sfocata e con colori meno vivaci.

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!Determina il tipo di salto frame (fotogramma) applicato durante il gioco.\n
!il salto frame puo' migliorare la velocita' di emulazione di molti giochi.\n
!Off:    Non salta nessun frames (fotogramma).\n
!Auto:   Salta fino a N frames (N impostato in opzione successiva) se necessario.\n
!Manual: Renderizza solo 1 un frame ogni N + 1.

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!per l'auto frameskip: determina il massimo numero di frames che\n
!possono essere saltati consecutivamente.\n
!per il manual frameskip: determina il numero di frames che saranno\n
!sempre saltati.

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!Se alcuni oggetti appaiono e scompaiono durante il gioco per certi valori di salto\n
!frames impostati manualmente, cambiate il valore di questa opzione in 'random' per\n
!ridurre tale effetto. Altrimenti NON usate questa opzione,in quanto tende a\n
!peggiorare la qualita' dell'immagine, speciamente nelle azioni molto veloci.

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!Selezionare 'no' per disattivare completamente l'audio. Cio comportera'\n
!un significativo aumento della velocita' di emulazione.

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!Setta la dimensione (in bytes) del buffer audio. Valori alti possono\n
!dare prestazioni leggermente migliori al costo della latenza; valori\n
!piu bassi daranno un audio piu' sincronizzato.\n
!questa opzione richiede che il gpSP venga riavviato per poter essere attivata.

# MSG_G_S_MENU_HELP_7
#screen shot
!cattura l'immagine del gioco nella finestra a destra in XMB-Foto-MS-capture

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!Ritorna al menu principale.

# MSG_G_S_MENU_HELP_9
#TV output ratio
#
#
#
!TV output ratio
!
!
!

# MSG_G_S_MENU_HELP_10
#TV output interlace
#
#
#
!TV output interlace
!
!
!

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----------  --/--/----  --:--:--
!----/--/--  ----------  --:--:--

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#----------  --/--/----  --:--:--
!----------  --/--/----  --:--:--

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#----------  --/--/----  --:--:--
!----------  --/--/----  --:--:--

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot.
!Non esiste alcun savestate per questo slot.

# MSG_STATE_MENU_TITLE
#Savestate options:
!Opzioni Savestate:

# MSG_STATE_MENU_0
#Load savestate from current slot
!Carica savestate dallo slot corrente

# MSG_STATE_MENU_1
#Save savestate to current slot
!Salva il savestate nello slot in uso

# MSG_STATE_MENU_2
#Load savestate from file
!carica savestate da file

# MSG_STATE_MENU_3
#Current savestate slot: %d
!savestate slot corrente: %d

# MSG_STATE_MENU_4
#Back
!indietro

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!Seleziona per caricare il game state dallo slot corrente per questa ROM.\n
!Premere destra/sinistra D-pad per cambiare lo slot corrente.

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!Seleziona per salvare il game state nello slot corrente per questa ROM.\n
!Premere destra/sinistra D-pad per cambiare lo slot corrente.

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.\n
!Ripristina lo stato del gioco da un savestate.\n
!Nota: il savestate deve essere presente sulla memstick.\n

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.\n
!Cambia lo slot corrente per i savestate.\n

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!Ritorna al menu principale.

# MSG_PAD_MENU_0
#D-pad up     : %s
!D-pad su      : %s

# MSG_PAD_MENU_1
#D-pad down   : %s
!D-pad giu'    : %s

# MSG_PAD_MENU_2
#D-pad left   : %s
!D-pad sinistra: %s

# MSG_PAD_MENU_3
#D-pad right  : %s
!D-pad destra  : %s

# MSG_PAD_MENU_4
#Circle       : %s
!Cerchio       : %s

# MSG_PAD_MENU_5
#Cross        : %s
!Croce         : %s

# MSG_PAD_MENU_6
#Square       : %s
!Quadrato      : %s

# MSG_PAD_MENU_7
#Triangle     : %s
!Triangolo     : %s

# MSG_PAD_MENU_8
#Left Trigger : %s
!Left Trigger  : %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!Right Trigger : %s

# MSG_PAD_MENU_10
#Start        : %s
!Start         : %s

# MSG_PAD_MENU_11
#Select       : %s
!Select        : %s

# MSG_PAD_MENU_12
#Back
!Ritorna

# MSG_PAD_MENU_HELP_0
#Return to the main menu.
!Ritorna al menu principale.

#PADの設定 コンフィグ

# MSG_PAD_MENU_CFG_0
#UP
!SU

# MSG_PAD_MENU_CFG_1
#DOWN
!Giu

# MSG_PAD_MENU_CFG_2
#LEFT
!Sinistra

# MSG_PAD_MENU_CFG_3
#RIGHT
!Destra

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!START

# MSG_PAD_MENU_CFG_9
#SELECT
!SELECT

# MSG_PAD_MENU_CFG_10
#MENU
!MENU

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!FASTFORWARD

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!LOAD STATE

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!SAVE STATE

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!RAPIDFIRE A

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!RAPIDFIRE B

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!RAPIDFIRE L

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!RAPIDFIRE R

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!VOLUME UP

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!VOLUME DOWN

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!DISPLAY FPS

# MSG_PAD_MENU_CFG_21
#NOTHING
!NULLA

# MSG_PAD_MENU_HELP_0
#Up button on GBA d-pad.
!pulsante SU del d-pad GBA.

# MSG_PAD_MENU_HELP_1
#Down button on GBA d-pad.
!pulsante GIU del d-pad GBA.

# MSG_PAD_MENU_HELP_2
#Left button on GBA d-pad.
!pulsante SX del d-pad GBA.

# MSG_PAD_MENU_HELP_3
#Right button on GBA d-pad.
!pulsante DX del d-pad GBA.

# MSG_PAD_MENU_HELP_4
#A button on GBA.
!pulsante A del GBA.

# MSG_PAD_MENU_HELP_5
#B button on GBA.
!pulsante B del GBA.

# MSG_PAD_MENU_HELP_6
#Left shoulder button on GBA.
!Grilletto sinistro del GBA.

# MSG_PAD_MENU_HELP_7
#Right shoulder button on GBA.
!Grilletto destro del GBA.

# MSG_PAD_MENU_HELP_8
#Start button on GBA.
!pulsante Start del GBA.

# MSG_PAD_MENU_HELP_9
#Select button on GBA.
!pulsante Select del GBA.

# MSG_PAD_MENU_HELP_10
#Brings up the options menu.
!Vai direttamente al menu.

# MSG_PAD_MENU_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!Attiva accellerazione on/off (non aspettatevi grandi risultati)

# MSG_PAD_MENU_HELP_12
#Loads the game state from the current slot.
!carica il gamestate dallo slot corrente.

# MSG_PAD_MENU_HELP_13
#Saves the game state to the current slot.
!Salva il gamestate nello slot corrente.

# MSG_PAD_MENU_HELP_14
#Rapidly press/release the A button on GBA.
!Autofire per il pulsante A del GBA (tenere premuto).

# MSG_PAD_MENU_HELP_15
#Rapidly press/release the B button on GBA.
!Autofire per il pulsante B del GBA (tenere premuto).

# MSG_PAD_MENU_HELP_16
#Rapidly press/release the Left shoulder button on GBA.
!Autofire per il Grilletto SX del GBA (tenere premuto).

# MSG_PAD_MENU_HELP_17
#Rapidly press/release the Right shoulder button on GBA.
!Autofire per il Grilletto DX del GBA (tenere premuto).

# MSG_PAD_MENU_HELP_18
#Increases the volume.
!Increases the volume.

# MSG_PAD_MENU_HELP_19
#Decreases the volume.
!Decreases the volume.

# MSG_PAD_MENU_HELP_20
#Displays virtual/drawn frames per second.
!Displays virtual/drawn frames per second.

# MSG_PAD_MENU_HELP_21
#Does nothing.
!Non fa nulla.

# MSG_A_PAD_MENU_0
#Analog up   : %s
!Analogico  SU: %s

# MSG_A_PAD_MENU_1
#Analog down : %s
!Analogico Giu: %s

# MSG_A_PAD_MENU_2
#Analog left : %s
!Analog SX    : %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!Analog DX    : %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!Attiva analog: %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!Analog sensitivity: %d

# MSG_A_PAD_MENU_6
#Back
!Indietro

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!Seleziona 'no' per bloccare completamente il pad analogico.

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!Determina la sensibilita' del pad analogico.\n
!Valori bassi richiedono movimenti piu' ampi.

# MSG_A_PAD_MENU_HELP_2
#Return to the main menu.
!Ritorna al menu principale.

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!cheat %d (non caricato)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!cheat %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!Carica file Trucchi

# MSG_CHEAT_MENU_2
#Clock speed: %s
!Velocita' processore: %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!Aggiorna Salvataggio: %s

# MSG_CHEAT_MENU_4
#Back
!Indietro

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!Attiva/disattiva il codice del Trucco.

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
!Carica un file per i Trucchi

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!Cambia il clock del processore della PSP. Valori piu' alti producono\n
!prestazioni migliori, ma riducono la durata delle batterie.

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!Determina quando i salvataggi del gioco saranno scritti sulla memstick.\n
!Se impostato su 'automatic' la scrittura avverra' quando si effettua un\n
!salvataggio durante il gioco. impostato su 'exit only' sara' scritto\n
!solo all'uscita da questo menu (NON con il pulsante home della PSP).\n
!Usate l'ultima opzione con estrema attenzione.

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!Ritorna al menu principale.

# MSG_NON_LOAD_GAME
#No game loaded yet.
!Nessuna rom e' stata caricata.

# MSG_WDAY_0
#Sunday
!Domenica

# MSG_WDAY_1
#Monday
!Lunedi

# MSG_WDAY_2
#Martedi
!Martedi

# MSG_WDAY_3
#Wednesday
!Mercoledi

# MSG_WDAY_4
#Thursday
!Giovedi

# MSG_WDAY_5
#Friday
!Venerdi

# MSG_WDAY_6
#Saturday
!Sabato

# MSG_YES
#yes
!SI

# MSG_NO
#no
!no

# MSG_ENABLED
#enabled
!Attivato

# MSG_DISABLED
#disabled
!disattivato

# MSG_SCALE_UNSCALED
#unscaled 3:2
!unscaled 3:2

# MSG_SCALE_SCALED
#scaled 3:2
!scaled 3:2

# MSG_SCALE_FULL
#fullscreen 16:9
!fullscreen 16:9

# MSG_SCN_OPT1
#option 1
!option 1

# MSG_SCN_OPT2
#option 2
!option 2

# MSG_FS_AUTO
#automatic
!automatic

# MSG_FS_MANUAL
#manual
!manual

# MSG_FS_OFF
#off
!off

# MSG_FS_UNIFORM
#uniform
!uniform

# MSG_FS_RAMDOM
#random
!random

# MSG_SB_2048
#2048 bytes
!2048 bytes

# MSG_SB_3072
#3072 bytes
!3072 bytes

# MSG_SB_4096
#4096 bytes
!4096 bytes

# MSG_SB_5120
#5120 bytes
!5120 bytes

# MSG_SB_6144
#6144 bytes
!6144 bytes

# MSG_SB_7168
#7168 bytes
!7168 bytes

# MSG_SB_8192
#8192 bytes
!8192 bytes

# MSG_SB_9216
#9216 bytes
!9216 bytes

# MSG_SB_10240
#10240 bytes
!10240 bytes

# MSG_SB_11264
#11264 bytes
!11264 bytes

# MSG_SB_12288
#12288 bytes
!12288 bytes

# MSG_BK_EXITONLY
#Exit only
!Exit only

# MSG_BK_AUTO
#Automatic
!Automatic

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%02d_%02d_%04d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!Spiacente, ma il gpSP richiede un'immagine del BIOS Gameboy Advance per\n
!funzionare correttamente. Verificate di averne una autentica (cercate sul\n
!Web o chiedete ai vostri amici, ma non chiedetela all'autore del gpSP\n
!o sarete bannati e odiati), l'immagine ha esattamente la dimensione di\n
!16384 bytes e il seguente valore di md5sum:\n\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!a860e8c0b6d573d191e4ec7db1b1e4f6 o 1c0d67db9e1208b95a1506b1688a0ad6\n\n
!Altri BIOS potrebbero funzionare parzialmente o perfettamente\n
!Ma non sono stati testati dall'autore del programma.\n\n
!L'immagine deve essere rinominata gba_bios.bin e salvata nella\n
!stessa cartella dell'EBOOT del gpSP.\n\n
!Buona fortuna. Premere qualunque pulsante per uscire.\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!Questo bios non e' stato testato con il gpSP.\n
!Si potrebbero verificare problemi nell'emulazione.\n
!Usate BIOS con MD5= a860e8c0b6d573d191e4ec7db1b1e4f6.\n
!o MD5= 1c0d67db9e1208b95a1506b1688a0ad6.\n

# MSG_R_4_3
#ratio 4:3
!ratio 4:3

# MSG_R_16_9
#ratio 16:9
!ratio 16:9

# MSG_I_NON
#progressive
!progressive

# MSG_I_ON
#interlace
!interlace

# MSG_INIT_END
#Initialization end
!Initialization end

# MSG_LOAD_STATE
#Load State.
!Load State.

# MSG_LOAD_STATE_END
#Load State End.
!Load State End.

# MSG_SAVE_STATE
#Save State.
!Save State.

# MSG_SAVE_STATE_END
#Save State End.
!Save State End.

# MSG_CHEAT_MENU_5
#cheat page: %d
!cheat page: %d

# MSG_CHEAT_MENU_HELP_5
#cheat page
!cheat page

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Enable HOME: %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!Enable HOME

# MSG_PAD_MENU_13,
#Use dafault map : %s
!Use dafault map : %s

# MSG_PAD_MENU_HELP13,
#Use dafault map
!Use dafault map

