# messege file
# Japanese

# MSG_RETURN_MENU
#Press X to return to the main menu.
!×ボタンでメインメニューに戻ります

# MSG_MENU_DATE
#TIME 
!時刻 

# MSG_MENU_BATTERY
#battery LifePercent:%3d%% LifeTime:%3dmin.
!バッテリー 残量:%3d%% 残時間:%3d分

# MSG_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_MAIN_MENU_0
#Graphics and Sound options
!グラフィック/サウンドの設定

# MSG_MAIN_MENU_1
#Load state from slot: %d
!ロードステート スロット: %d

# MSG_MAIN_MENU_2
#Save state to slot: %d
!セーブステート スロット: %d

# MSG_MAIN_MENU_3
#Savestate options
!ステートセーブの設定

# MSG_MAIN_MENU_4
#Configure gamepad input
!キーの設定

# MSG_MAIN_MENU_5
#Configure analog input
!アナログパッドの設定

# MSG_MAIN_MENU_6
#Cheats and Miscellaneous options
!チート/その他の設定

# MSG_MAIN_MENU_7
#Load new game
!ゲームのロード

# MSG_MAIN_MENU_8
#Restart game
!リセット

# MSG_MAIN_MENU_9
#Return to game
!ゲームに戻る

# MSG_MAIN_MENU_10
#Exit gpSP
!gpSPの終了

# MSG_MAIN_MENU_HELP_0
#Select to set display parameters and frameskip behavior,\n
#audio on/off, audio buffer size, and audio filtering.
!画面、フレームスキップ、オーディオの設定を変更します。\n
!

# MSG_MAIN_MENU_HELP_1
#Select to load the game state from the current slot for this game,\n
#if it exists (see the extended menu for more information)\n
#Press left + right to change the current slot.
!現在のスロットからステートをロードします\n
!(ゲームステートが保存されている場合)(詳細は拡張メニューに表示)\n
!L+Rでスロットを変更します

# MSG_MAIN_MENU_HELP_2
#Select to save the game state to the current slot for this game.\n
#See the extended menu for more information.\n
#Press left + right to change the current slot.
!現在のスロットにステートをセーブします\n
!詳細は拡張メニューに表示\n
!L+Rでスロットを変更します

# MSG_MAIN_MENU_HELP_3
#Select to enter a menu for loading, saving, and viewing the\n
#currently active savestate for this game (or to load a savestate\n
#file from another game)
!このゲームに関して現在使用されているセーブステートをロード、セーブ、見るためにメニュー\n
!に記録するために、選びます。\n
!(また、もうひとつのゲームからセーブステートファイルをロードするために)

# MSG_MAIN_MENU_HELP_4
#Select to change the in-game behavior of the PSP buttons and d-pad.
!十時キー及びボタンの設定を変更します

# MSG_MAIN_MENU_HELP_5
#Select to change the in-game behavior of the PSP analog nub.
!アナログパッドの設定を変更します

# MSG_MAIN_MENU_HELP_6
#Select to manage cheats, set backup behavior, and set device clock\n
#speed.
!チート、バックアップのタイミング、PSPのクロックを変更します
!

# MSG_MAIN_MENU_HELP_7
#Select to load a new game (will exit a game if currently playing).
!別のゲームをロードします(キャンセルした場合は今のゲームを続行します)

# MSG_MAIN_MENU_HELP_8
#Select to reset the GBA with the current game loaded.
!現在ロードしているゲームをリセットします

# MSG_MAIN_MENU_HELP_9
#Select to exit this menu and resume gameplay.
!メニューを閉じてゲームに戻ります

# MSG_MAIN_MENU_HELP_10
#Select to exit gpSP and return to the PSP XMB/loader.
!gpSPを終了してXMB/loaderに戻ります

# MSG_G_S_MENU_0
#Display scaling: %s
!画面表示: %s

# MSG_G_S_MENU_1
#Screen filtering: %s
!画面のフィルタリング: %s

# MSG_G_S_MENU_2
#Frameskip type: %s
!フレームスキップの種類: %s

# MSG_G_S_MENU_3
#Frameskip value: %d
!フレームスキップの値: %d

# MSG_G_S_MENU_4
#Framskip variation: %s
!フレームスキップの種類: %s

# MSG_G_S_MENU_5
#Audio output: %s
!オーディオ出力: %s

# MSG_G_S_MENU_6
#Audio buffer: %s
!オーディオ バッファ: %s

# MSG_G_S_MENU_7
#screen shot
!スクリーン ショット

# MSG_G_S_MENU_8
#Back
!戻る

# MSG_G_S_MENU_9
#TV output ratio       : %s
!TV output ratio       : %s

# MSG_G_S_MENU_10
#TV output interlace   : %s
!TV output interlace   : %s

# MSG_G_S_MENU_HELP_0
#Determines how the GBA screen is resized in relation to the entire\n
#screen. Select unscaled 3:2 for GBA resolution, scaled 3:2 for GBA\n
#aspect ratio scaled to fill the height of the PSP screen, and\n
#fullscreen to fill the entire PSP screen.
!スクリーンがどのように全体のスクリーンと関連してリサイズされるかを決定します。\n
!GBA規格と同じ大きさ：拡大なし 3:2\n
!PSPの画面の縦の長さとGBAのアスペクト比が一致：拡大 3:2\n
!PSP全体に拡大した大きさ：フルスクリーン

# MSG_G_S_MENU_HELP_1
#Determines whether or not bilinear filtering should be used when\n
#scaling the screen. Selecting this will produce a more even and\n
#smooth image, at the cost of being blurry and having less vibrant\n
#colors.
!スクリーンを拡大するとき、フィルタリングを使用するかどうかを決定します。\n
!これを選択すると、より均等で滑らかなイメージを作り出します。\n
!しかし、ぼやけた、あまり明るくない色になります。\n
!

# MSG_G_S_MENU_HELP_2
#Determines what kind of frameskipping should be employed.\n
#Frameskipping may improve emulation speed of many games.\n
#Off: Do not skip any frames.\n
#Auto: Skip up to N frames (see next option) as needed.\n
#Manual: Always render only 1 out of N + 1 frames.
!どの種類のフレームスキップを使用するかを決定します。\n
!フレームスキップすることで多くのゲームの速度が向上するかもしれません。\n
!オフ : フレームスキップを使用しません。\n
!自動 : 必要に応じてNフレーム(次のオプションを見る)スキップします。\n
!手動 : 毎回N+1フレームから1だけをフレームスキップします。

# MSG_G_S_MENU_HELP_3
#For auto frameskip, determines the maximum number of frames that\n
#are allowed to be skipped consecutively.\n
#For manual frameskip, determines the number of frames that will\n
#always be skipped.
!自動でフレームスキップするために、連続してスキップすることができるフレームの最大数\n
!を決定します。\n
!手動でフレームスキップするために、いつもスキップされるフレームの数を決定します。\n
!

# MSG_G_S_MENU_HELP_4
#If objects in the game flicker at a regular rate certain manual\n
#frameskip values may cause them to normally disappear. Change this\n
#value to 'random' to avoid this. Do not use otherwise, as it tends to\n
#make the image quality worse, especially in high motion games.
!ゲームにおける物が普通の値の手動のフレームスキップで明滅するなら、フレームスキップの\n
!値によってはそれらは見えなくなるかもしれません。\n
!これを避けるために'ランダム'に変えてください。 そうでなければ、画質をより悪くする傾向\n
!がある、特に高い動きのゲームには使用しないでください。

# MSG_G_S_MENU_HELP_5
#Select 'no' to turn off all audio output. This will not result in a\n
#significant change in performance.
!すべてのオーディオ出力をオフにするためには'いいえ'を選択してください。\n
!これはパフォーマンスにおいてあまり変化をもたらさないでしょう。

# MSG_G_S_MENU_HELP_6
#Set the size (in bytes) of the audio buffer. Larger values may result\n
#in slightly better performance at the cost of latency; the lowest\n
#value will give the most responsive audio.\n
#This option requires gpSP to be restarted before it will take effect.
!オーディオバッファのサイズ(バイトによる)を設定します。\n
!大きい値はわずかにパフォーマンスを高めるかもしれませんが、時間がかかるかもしれません。\n
!最も低い値にするととても良い音になるでしょう。\n
!このオプションは、設定が反映されるためにgpSPを再起動する必要があります。

# MSG_G_S_MENU_HELP_7
#screen shot
!スクリーン ショット

# MSG_G_S_MENU_HELP_8
#Return to the main menu.
!メインメニューに戻る

# MSG_G_S_MENU_HELP_9
#TV output ratio
#
#
#
!TV output ratio
!
!
!

# MSG_G_S_MENU_HELP_10
#TV output interlace
#
#
#
!TV output interlace
!
!
!

# MSG_STATE_MENU_DATE_FMT_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%04d/%02d/%02d  %-10s  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%-10s  %02d/%02d/%04d  %02d:%02d:%02d          
!%-10s  %02d/%02d/%04d  %02d:%02d:%02d          

# MSG_STATE_MENU_DATE_NONE_0
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#----------  --/--/----  --:--:--          
!----/--/--  ----------  --:--:--          

# MSG_STATE_MENU_DATE_NONE_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#----------  --/--/----  --:--:--          
!----------  --/--/----  --:--:--          

# MSG_STATE_MENU_DATE_NONE_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#----------  --/--/----  --:--:--          
!----------  --/--/----  --:--:--          

# MSG_STATE_MENU_STATE_NONE
#No savestate exists for this slot.
!このスロットにステートデータはありません

# MSG_STATE_MENU_TITLE
#Savestate options:
!セーブステートの設定:

# MSG_STATE_MENU_0
#Load savestate from current slot
!現在のスロットからステートをロード

# MSG_STATE_MENU_1
#Save savestate to current slot
!現在のスロットにステートをセーブ

# MSG_STATE_MENU_2
#Load savestate from file
!ファイルからステートをロード

# MSG_STATE_MENU_3
#Current savestate slot: %d
!現在のステートのスロット: %d

# MSG_STATE_MENU_4
#Back
!戻る

# MSG_STATE_MENU_HELP_0
#Select to load the game state from the current slot for this game.\n
#Press left + right to change the current slot.
!現在のスロットからステートをロード\n
!L+Rで現在のスロットを変更

# MSG_STATE_MENU_HELP_1
#Select to save the game state to the current slot for this game.\n
#Press left + right to change the current slot.
!現在のスロットへステートをセーブ\n
!L+Rで現在のスロットを変更

# MSG_STATE_MENU_HELP_2
#Restore gameplay from a savestate file.\n
#Note: The same file used to save the state must be present.\n
!セーブステートからゲームプレイを復元してください。\n
!注意:ステートセーブするのに使用される同じファイルは存在していなければなりません。\n

# MSG_STATE_MENU_HELP_3
#Change the current savestate slot.\n
!ステートスロットの変更\n

# MSG_STATE_MENU_HELP_4
#Return to the main menu.
!メインメニューに戻る

# MSG_PAD_MENU_0
#D-pad up     : %s
!↑　　　　　 : %s

# MSG_PAD_MENU_1
#D-pad down   : %s
!↓　　　　　 : %s

# MSG_PAD_MENU_2
#D-pad left   : %s
!←　　　　　 : %s

# MSG_PAD_MENU_3
#D-pad right  : %s
!→　　　　　 : %s

# MSG_PAD_MENU_4
#Circle       : %s
!○　　　　　 : %s

# MSG_PAD_MENU_5
#Cross        : %s
!×　　　　　 : %s

# MSG_PAD_MENU_6
#Square       : %s
!□　　　　　 : %s

# MSG_PAD_MENU_7
#Triangle     : %s
!△　　　　　 : %s

# MSG_PAD_MENU_8
#Left Trigger : %s
!左トリガー　 : %s

# MSG_PAD_MENU_9
#Right Trigger: %s
!右トリガー　 : %s

# MSG_PAD_MENU_10
#Start        : %s
!スタート　　 : %s

# MSG_PAD_MENU_11
#Select       : %s
!セレクト　　 : %s

# MSG_PAD_MENU_12
#Back
!戻る

# MSG_PAD_MENU_HELP_0
#Return to the main menu.
!メインメニューに戻る.

#PADの設定 コンフィグ

# MSG_PAD_MENU_CFG_0
#UP
!↑

# MSG_PAD_MENU_CFG_1
#DOWN
!↓

# MSG_PAD_MENU_CFG_2
#LEFT
!←

# MSG_PAD_MENU_CFG_3
#RIGHT
!→

# MSG_PAD_MENU_CFG_4
#A
!A

# MSG_PAD_MENU_CFG_5
#B
!B

# MSG_PAD_MENU_CFG_6
#L
!L

# MSG_PAD_MENU_CFG_7
#R
!R

# MSG_PAD_MENU_CFG_8
#START
!スタート

# MSG_PAD_MENU_CFG_9
#SELECT
!セレクト

# MSG_PAD_MENU_CFG_10
#MENU
!メニュー

# MSG_PAD_MENU_CFG_11
#FASTFORWARD
!ターボ

# MSG_PAD_MENU_CFG_12
#LOAD STATE
!ステートロード

# MSG_PAD_MENU_CFG_13
#SAVE STATE
!ステートセーブ

# MSG_PAD_MENU_CFG_14
#RAPIDFIRE A
!A連射

# MSG_PAD_MENU_CFG_15
#RAPIDFIRE B
!B連射

# MSG_PAD_MENU_CFG_16
#RAPIDFIRE L
!L連射

# MSG_PAD_MENU_CFG_17
#RAPIDFIRE R
!R連射

# MSG_PAD_MENU_CFG_18
#VOLUME UP
!VOLUME UP

# MSG_PAD_MENU_CFG_19
#VOLUME DOWN
!VOLUME DOWN

# MSG_PAD_MENU_CFG_20
#DISPLAY FPS
!DISPLAY FPS

# MSG_PAD_MENU_CFG_21
#NOTHING
!なし

# MSG_PAD_MENU_HELP_0
#Up button on GBA d-pad.
!↑ボタンを割当て

# MSG_PAD_MENU_HELP_1
#Down button on GBA d-pad.
!↓ボタンを割当て

# MSG_PAD_MENU_HELP_2
#Left button on GBA d-pad.
!←ボタンを割当て

# MSG_PAD_MENU_HELP_3
#Right button on GBA d-pad.
!→ボタンを割当て

# MSG_PAD_MENU_HELP_4
#A button on GBA.
!Aボタンを割当て

# MSG_PAD_MENU_HELP_5
#B button on GBA.
!Bボタンを割当て

# MSG_PAD_MENU_HELP_6
#Left shoulder button on GBA.
!Lボタンを割当て

# MSG_PAD_MENU_HELP_7
#Right shoulder button on GBA.
!Rボタンを割当て

# MSG_PAD_MENU_HELP_8
#Start button on GBA.
!スタートボタンを割当て

# MSG_PAD_MENU_HELP_9
#Select button on GBA.
!セレクトボタンを割当て

# MSG_PAD_MENU_HELP_10
#Brings up the options menu.
!メニューを割当て

# MSG_PAD_MENU_HELP_11
#Toggles fastforward on/off (don't expect it to do much or anything)
!ターボのオン/オフ

# MSG_PAD_MENU_HELP_12
#Loads the game state from the current slot.
!ステートロードを割当て

# MSG_PAD_MENU_HELP_13
#Saves the game state to the current slot.
!ステートセーブを割当て

# MSG_PAD_MENU_HELP_14
#Rapidly press/release the A button on GBA.
!Ａ連射を割当て

# MSG_PAD_MENU_HELP_15
#Rapidly press/release the B button on GBA.
!Ｂ連射を割当て

# MSG_PAD_MENU_HELP_16
#Rapidly press/release the L shoulder button on GBA.
!Ｌ連射を割当て

# MSG_PAD_MENU_HELP_17
#Rapidly press/release the R shoulder button on GBA.
!Ｒ連射を割当て

# MSG_PAD_MENU_HELP_18
#Increases the volume.
!Increases the volume.

# MSG_PAD_MENU_HELP_19
#Decreases the volume.
!Decreases the volume.

# MSG_PAD_MENU_HELP_20
#Displays virtual/drawn frames per second.
!Displays virtual/drawn frames per second.

# MSG_PAD_MENU_HELP_21
#Does nothing.
!割当てなし

# MSG_A_PAD_MENU_0
#Analog up   : %s
!アナログ ↑ : %s

# MSG_A_PAD_MENU_1
#Analog down : %s
!アナログ ↓ : %s

# MSG_A_PAD_MENU_2
#Analog left : %s
!アナログ ← : %s

# MSG_A_PAD_MENU_3
#Analog right: %s
!アナログ → : %s

# MSG_A_PAD_MENU_4
#Enable analog: %s
!アナログの有効: %s

# MSG_A_PAD_MENU_5
#Analog sensitivity: %d
!アナログ入力の感度: %d

# MSG_A_PAD_MENU_6
#Back
!戻る

# MSG_A_PAD_MENU_HELP_0
#Select 'no' to block analog input entirely.
!アナログパッドにキー割り当てをしない場合、 入力が無効になります

# MSG_A_PAD_MENU_HELP_1
#Determine sensitivity/responsiveness of the analog input.\n
#Lower numbers are less sensitive.
!アナログ入力の感度/応答を設定\n
!数字が小さいほど感度が低くなります 

# MSG_A_PAD_MENU_HELP_2
#Return to the main menu.
!メインメニューに戻る

# MSG_CHEAT_MENU_NON_LOAD
#cheat %d (none loaded)
!cheat %d (未ロード)

# MSG_CHEAT_MENU_0
#cheat %d (%s): %%s
!cheat %d (%s): %%s

# MSG_CHEAT_MENU_1
#Load Cheat File
!チートファイル ロード

# MSG_CHEAT_MENU_2
#Clock speed: %s
!クロックの速度: %s

# MSG_CHEAT_MENU_3
#Update backup: %s
!バックアップの更新: %s

# MSG_CHEAT_MENU_4
#Back
!戻る

# MSG_CHEAT_MENU_HELP_0
#Activate/deactivate this cheat code.
!選択したコードの有効/無効の切替

# MSG_CHEAT_MENU_HELP_1
# Load Cheat File
!チートファイルのロード

# MSG_CHEAT_MENU_HELP_2
#Change the clock speed of the device. Higher clock speed will yield\n
#better performance, but will use drain battery life further.
!クロックの速度を変更します。高くすれば高いパフォーマンスを発揮します。\n
!しかし、バッテリーの寿命が通常より減る可能性があります。

# MSG_CHEAT_MENU_HELP_3
#Determines when in-game save files should be written back to\n
#memstick. If set to 'automatic' writebacks will occur shortly after\n
#the game's backup is altered. On 'exit only' it will only be written\n
#back when you exit from this menu (NOT from using the home button).\n
#Use the latter with extreme care.
!ゲームで、セーブデータがいつMSに書き込まれるかを決定します。\n
!'自動'に設定した場合、ゲームのバックアップが変更された後すぐに書き込まれます。\n
!'終了時'では、(HOMEボタンも含め)終了するときだけ、書き込まれます。\n
!過度に注意をするのなら後者を使用してください。\n
!

# MSG_CHEAT_MENU_HELP_4
#Return to the main menu.
!メインメニューに戻る

# MSG_NON_LOAD_GAME
#No game loaded yet.
!未ロード.     

# MSG_WDAY_0
#Sunday
!日曜

# MSG_WDAY_1
#Monday
!月曜

# MSG_WDAY_2
#Tuesday
!火曜

# MSG_WDAY_3
#Wednesday
!水曜

# MSG_WDAY_4
#Thursday
!木曜

# MSG_WDAY_5
#Friday
!金曜

# MSG_WDAY_6
#Saturday
!土曜

# MSG_YES
#yes
!はい

# MSG_NO
#no
!いいえ

# MSG_ENABLED
#enabled
!有効

# MSG_DISABLED
#disabled
!無効

# MSG_SCALE_UNSCALED
#unscaled 3:2
!拡大なし 3:2

# MSG_SCALE_SCALED
#scaled 3:2
!拡大 3:2

# MSG_SCALE_FULL
#fullscreen 16:9
!フルスクリーン 16:9

# MSG_SCN_OPT1
#option 1
!オプション 1

# MSG_SCN_OPT2
#option 2
!オプション 2

# MSG_FS_AUTO
#automatic
!自動

# MSG_FS_MANUAL
#manual
!手動

# MSG_FS_OFF
#off
!オフ

# MSG_FS_UNIFORM
#uniform
!一定

# MSG_FS_RAMDOM
#random
!ランダム

# MSG_SB_2048
#2048 bytes
!2048 バイト

# MSG_SB_3072
#3072 bytes
!3072 バイト

# MSG_SB_4096
#4096 bytes
!4096 バイト

# MSG_SB_5120
#5120 bytes
!5120 バイト

# MSG_SB_6144
#6144 bytes
!6144 バイト

# MSG_SB_7168
#7168 bytes
!7168 バイト

# MSG_SB_8192
#8192 bytes
!8192 バイト

# MSG_SB_9216
#9216 bytes
!9216 バイト

# MSG_SB_10240
#10240 bytes
!10240 バイト

# MSG_SB_11264
#11264 bytes
!11264 バイト

# MSG_SB_12288
#12288 bytes
!12288 バイト

# MSG_BK_EXITONLY
#Exit only
!終了時

# MSG_BK_AUTO
#Automatic
!自動

# MSG_CLK_33
#33MHz
!33MHz

# MSG_CLK_66
#66MHz
!66MHz

# MSG_CLK_100
#100MHz
!100MHz

# MSG_CLK_133
#133MHz
!133MHz

# MSG_CLK_166
#166MHz
!166MHz

# MSG_CLK_200
#200MHz
!200MHz

# MSG_CLK_233
#233MHz
!233MHz

# MSG_CLK_266
#266MHz
!266MHz

# MSG_CLK_300
#300MHz
!300MHz

# MSG_CLK_333
#333MHz
!333MHz

# MSG_SS_FMT_1
# for PSP_SYSTEMPARAM_DATE_FORMAT_YYYYMMDD
#%02d_%02d_%04d_%s%02d_%02d_%02d_%03d
!%04d_%02d_%02d_%s%02d_%02d_%02d_%03d

# MSG_SS_FMT_2
# for PSP_SYSTEMPARAM_DATE_FORMAT_MMDDYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_SS_FMT_3
# for PSP_SYSTEMPARAM_DATE_FORMAT_DDMMYYYY
#%s%02d_%02d_%04d_%02d_%02d_%02d_%03d
!%s%02d_%02d_%04d_%02d_%02d_%02d_%03d

# MSG_ERR_BIOS_1
#Sorry, but gpSP requires a Gameboy Advance BIOS image to run\n
#correctly. Make sure to get an authentic one (search the web,\n
#beg other people if you want, but don't hold me accountable\n
#if you get hated or banned for it), it'll be exactly 16384\n
#bytes large and should have the following md5sum value:\n\n
!BIOSファイルが見つかりません。\n
!gpSPはBIOSファイルがないと起動できません\n
!16384バイトのBIOSファイルをgba_bios.binの名前で\n
!EBOOT.PBPと同じフォルダに配置して下さい。\n
!\n
!\n

# MSG_ERR_BIOS_2
#a860e8c0b6d573d191e4ec7db1b1e4f6 or 1c0d67db9e1208b95a1506b1688a0ad6\n\n
#Other BIOS files might work either partially completely, I\n
#really don't know.\n\n
#When you do get it name it gba_bios.bin and put it in the\n
#same directory as this EBOOT.\n\n
#Good luck. Press any button to exit.\n
!BIOSのMD5は以下の値になります\n
!GBAの場合：A860E8C0B6D573D191E4EC7DB1B1E4F6\n
!NDSの場合：1C0D67DB9E1208B95A1506B1688A0AD6\n
!違う場合は不具合のでる可能性がありますので注意して下さい。\n
!\n
!ボタンを押すと終了します。\n

# MSG_ERR_BIOS_MD5
#This BIOS is not regular.\n
#There is a possibility of various trouble.\n\n
#Please use regular BIOS.\n
!このBIOSは正規のものではありません。\n
!様々な不具合が出る可能性があります。\n\n
!正規のBIOSを使用してください。\n

# MSG_R_4_3
#ratio 4:3
!ratio 4:3

# MSG_R_16_9
#ratio 16:9
!ratio 16:9

# MSG_I_NON
#progressive
!progressive

# MSG_I_ON
#interlace
!interlace

# MSG_INIT_END
#Initialization end
!初期化終了

# MSG_LOAD_STATE
#Load State.
!Load State.

# MSG_LOAD_STATE_END
#Load State End.
!Load State End.

# MSG_SAVE_STATE
#Save State.
!Save State.

# MSG_SAVE_STATE_END
#Save State End.
!Save State End.

# MSG_CHEAT_MENU_5
#cheat page: %d
!cheat page: %d

# MSG_CHEAT_MENU_HELP_5
#cheat page
!cheat page

# MSG_CHEAT_MENU_6
#Enable HOME: %s
!Enable HOME: %s

# MSG_CHEAT_MENU_HELP_6
#Enable HOME
!Enable HOME

# MSG_PAD_MENU_13,
#Use dafault map : %s
!Use dafault map : %s

# MSG_PAD_MENU_HELP13,
#Use dafault map
!Use dafault map

